// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: upf.proto

package upf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SMF 向 UPF 下发转发规则
type CreateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话ID
	UeId          string                 `protobuf:"bytes,2,opt,name=ue_id,json=ueId,proto3" json:"ue_id,omitempty"`                // 设备ID
	UeIp          string                 `protobuf:"bytes,3,opt,name=ue_ip,json=ueIp,proto3" json:"ue_ip,omitempty"`                // UE的IP地址
	Dnn           string                 `protobuf:"bytes,4,opt,name=dnn,proto3" json:"dnn,omitempty"`                              // 数据网络名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleRequest) Reset() {
	*x = CreateRuleRequest{}
	mi := &file_upf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleRequest) ProtoMessage() {}

func (x *CreateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateRuleRequest) Descriptor() ([]byte, []int) {
	return file_upf_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRuleRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateRuleRequest) GetUeId() string {
	if x != nil {
		return x.UeId
	}
	return ""
}

func (x *CreateRuleRequest) GetUeIp() string {
	if x != nil {
		return x.UeIp
	}
	return ""
}

func (x *CreateRuleRequest) GetDnn() string {
	if x != nil {
		return x.Dnn
	}
	return ""
}

type CreateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RuleId        string                 `protobuf:"bytes,2,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"` // 转发规则ID
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRuleResponse) Reset() {
	*x = CreateRuleResponse{}
	mi := &file_upf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRuleResponse) ProtoMessage() {}

func (x *CreateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateRuleResponse) Descriptor() ([]byte, []int) {
	return file_upf_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateRuleResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *CreateRuleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除转发规则
type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_upf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_upf_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DeleteRuleRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_upf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_upf_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRuleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteRuleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查询转发规则（用于调试和监控）
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_upf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_upf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_upf_proto_rawDescGZIP(), []int{4}
}

func (x *GetStatsRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *GetStatsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RuleId           string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	UeIp             string                 `protobuf:"bytes,2,opt,name=ue_ip,json=ueIp,proto3" json:"ue_ip,omitempty"`
	PacketsForwarded uint64                 `protobuf:"varint,3,opt,name=packets_forwarded,json=packetsForwarded,proto3" json:"packets_forwarded,omitempty"` // 已转发包数量
	Active           bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	SessionId        string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UeId             string                 `protobuf:"bytes,6,opt,name=ue_id,json=ueId,proto3" json:"ue_id,omitempty"`
	Found            bool                   `protobuf:"varint,7,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_upf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_upf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_upf_proto_rawDescGZIP(), []int{5}
}

func (x *GetStatsResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *GetStatsResponse) GetUeIp() string {
	if x != nil {
		return x.UeIp
	}
	return ""
}

func (x *GetStatsResponse) GetPacketsForwarded() uint64 {
	if x != nil {
		return x.PacketsForwarded
	}
	return 0
}

func (x *GetStatsResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *GetStatsResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetStatsResponse) GetUeId() string {
	if x != nil {
		return x.UeId
	}
	return ""
}

func (x *GetStatsResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

var File_upf_proto protoreflect.FileDescriptor

const file_upf_proto_rawDesc = "" +
	"\n" +
	"\tupf.proto\x12\x03upf\"n\n" +
	"\x11CreateRuleRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05ue_id\x18\x02 \x01(\tR\x04ueId\x12\x13\n" +
	"\x05ue_ip\x18\x03 \x01(\tR\x04ueIp\x12\x10\n" +
	"\x03dnn\x18\x04 \x01(\tR\x03dnn\"a\n" +
	"\x12CreateRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\arule_id\x18\x02 \x01(\tR\x06ruleId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"K\n" +
	"\x11DeleteRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"H\n" +
	"\x12DeleteRuleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x0fGetStatsRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xcf\x01\n" +
	"\x10GetStatsResponse\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x13\n" +
	"\x05ue_ip\x18\x02 \x01(\tR\x04ueIp\x12+\n" +
	"\x11packets_forwarded\x18\x03 \x01(\x04R\x10packetsForwarded\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05ue_id\x18\x06 \x01(\tR\x04ueId\x12\x14\n" +
	"\x05found\x18\a \x01(\bR\x05found2\xc3\x01\n" +
	"\n" +
	"UPFService\x12=\n" +
	"\n" +
	"CreateRule\x12\x16.upf.CreateRuleRequest\x1a\x17.upf.CreateRuleResponse\x12=\n" +
	"\n" +
	"DeleteRule\x12\x16.upf.DeleteRuleRequest\x1a\x17.upf.DeleteRuleResponse\x127\n" +
	"\bGetStats\x12\x14.upf.GetStatsRequest\x1a\x15.upf.GetStatsResponseB\x1eZ\x1cgithub.com/5g-core/proto/upfb\x06proto3"

var (
	file_upf_proto_rawDescOnce sync.Once
	file_upf_proto_rawDescData []byte
)

func file_upf_proto_rawDescGZIP() []byte {
	file_upf_proto_rawDescOnce.Do(func() {
		file_upf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_upf_proto_rawDesc), len(file_upf_proto_rawDesc)))
	})
	return file_upf_proto_rawDescData
}

var file_upf_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_upf_proto_goTypes = []any{
	(*CreateRuleRequest)(nil),  // 0: upf.CreateRuleRequest
	(*CreateRuleResponse)(nil), // 1: upf.CreateRuleResponse
	(*DeleteRuleRequest)(nil),  // 2: upf.DeleteRuleRequest
	(*DeleteRuleResponse)(nil), // 3: upf.DeleteRuleResponse
	(*GetStatsRequest)(nil),    // 4: upf.GetStatsRequest
	(*GetStatsResponse)(nil),   // 5: upf.GetStatsResponse
}
var file_upf_proto_depIdxs = []int32{
	0, // 0: upf.UPFService.CreateRule:input_type -> upf.CreateRuleRequest
	2, // 1: upf.UPFService.DeleteRule:input_type -> upf.DeleteRuleRequest
	4, // 2: upf.UPFService.GetStats:input_type -> upf.GetStatsRequest
	1, // 3: upf.UPFService.CreateRule:output_type -> upf.CreateRuleResponse
	3, // 4: upf.UPFService.DeleteRule:output_type -> upf.DeleteRuleResponse
	5, // 5: upf.UPFService.GetStats:output_type -> upf.GetStatsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_upf_proto_init() }
func file_upf_proto_init() {
	if File_upf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_upf_proto_rawDesc), len(file_upf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_upf_proto_goTypes,
		DependencyIndexes: file_upf_proto_depIdxs,
		MessageInfos:      file_upf_proto_msgTypes,
	}.Build()
	File_upf_proto = out.File
	file_upf_proto_goTypes = nil
	file_upf_proto_depIdxs = nil
}
